### ISSUE TITLE
Update return to include closed issues, updated or created status.

### ISSUE THREAD

**Issue by tmelliottjr** [tmelliottjr/octokit-plugin-unique-issue#4]
`createOrUpdateUniqueIssue` should return more helpful information about the actions taken.

- List of closed issues when `close_previous` is `true`
- Whether or not an issue was created or updated

**Comment by gr2m** [comment]
you can amend the `response` object the plugin returns, that's what I do here for example:
https://github.com/octokit/plugin-create-or-update-text-file.js#create-or-update-existing-file-with-static-content (the plugin adds `response.deleted` and `response.updated`
